# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
