# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
