# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
