# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
